[package]
name = "firyx"
upgrade_policy = "compatible"
version = "1.0.0"
authors = []

[addresses]
firyx = "_"
admin = "0x57c528d90af4255748b37f3730afdda043fad019be735e7d899f5565840e0366"
deployer = "0xd548f6e8ef91c57e7983b1051df686a3753f3d453d37ef781782450e61079fe9"
dex_contract = "0x69faed94da99abb7316cb3ec2eeaa1b961a47349fad8c584f67a930b0d14fec7"

[dev-addresses]
firyx = "0x111"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-token-objects"

[dependencies.dex]
local = "./hyperfluid-interface"

[dev-dependencies]
